# POST http://localhost:3000/scenarios
# content-type: application/json

# {
# "scenario":"scenario 1",
# "connector":"connector 1",
# "connection":"connection 1",
# "tags":["tag 1","tag 2"],
# "trigger":"trigger 1",
# "status":"pending"
# }

#GET http://localhost:3000/scenarios
GET http://localhost:3000/scenarios/63b7bc0570f80eda5bfec975
# PUT  http://localhost:3000/scenarios
# Content-Type: application/x-www-form-urlencoded

# id=1&connection=test22222&tags=[test1, test2]&trigger=test1&status=test2
